### PR TITLE
Add deb and rpm build files and packpack auto build script

### PR DESCRIPTION
**Pull request by gdevenyi**
This is a complete set of build scripts for building packages for centos/redhat/fedora/debian/ubuntu.

Build happens locally and requires docker driven by the packpack build system: https://github.com/packpack/packpack

For master to build right now for some releases, mrisim module needs 020bb51d10b7679e8c210a3e6ac5b611e47349c0

Code includes auto-pushing of packages to packagecloud.io which offers free repositories for open source projects.

Builds broken:
centos-6 (el-6) - too old a version of libjpeg
ubuntu-precise - cmake missing SSL for downloads
debian-wheezy - cmake missing SSL for downloads

Example packages for all successful builds at  https://www.dropbox.com/sh/pah0ngr3rzu6j3j/AACLsWS1QoRhz1Rxeh-_2zSla?dl=0

Addresses #33

### CODE REVIEW

**Comment by vfonov** [comment]
how about 32bit builds ?

**Comment by vfonov** [comment]
how about 32bit builds?

**Comment by gdevenyi** [comment]
Hrm, never thought of those. I'll open up an issue for packpack to create some 32bit docker instances.

**Comment by gdevenyi** [comment]
P.S. These are ccache-enabled so they can be pretty quick if you make your cache big.

**Comment by vfonov** [comment]
Also, does it support building for macosx ?

**Comment by vfonov** [comment]
how big should be cache for ccache?

**Comment by gdevenyi** [comment]
I have a 20GB limit with 17GB full.

**Comment by gdevenyi** [comment]
Being docker based, there's unfortunately no OSX support.

**Comment by gdevenyi** [comment]
Oops one final warning, *.deb files all get the same name right now, so you'll need copy/rename them in the build loop or push them to packagecloud.

Tracking bug https://github.com/packpack/packpack/issues/11

**Pull request merged**
