### PR TITLE
Update to ITK 4.13.1

### PR DESCRIPTION
**Pull request by gdevenyi**

### CODE REVIEW

**Comment by gdevenyi** [comment]
Looks like my edit stripped a bunch of errant whitespace

**Comment by vfonov** [comment]
you might need to update https://github.com/BIC-MNI/minc-toolkit-v2/blob/develop-1.9.17/cmake-modules/PatchITKv4.cmake if the paths include .1

**Comment by gdevenyi** [comment]
The subpatch didn't change the directory name.

Also, full build and make test was successful.

**Comment by gdevenyi** [comment]
```
./external/opt/minc/1.9.17/lib/cmake/ITK-4.13
```

**Pull request merged**
