### PR TITLE
Fixes for 22.04 build

### PR DESCRIPTION
**Pull request by gdevenyi**
Addressing #153 and another bug I got bitten by.

### CODE REVIEW

**Comment by gdevenyi** [comment]
@bcdarwin

**Comment by gdevenyi** [comment]
https://github.com/BIC-MNI/mni_autoreg/pull/28/files pending

**Comment by gdevenyi** [comment]
These changes succeed in building on Ubuntu 22.04 under the following config
```
cmake ../minc-toolkit-v2 -DCMAKE_INSTALL_PREFIX=${install_prefix} \
        -DMT_BUILD_ABC=ON \
        -DMT_BUILD_ANTS=OFF \
        -DMT_BUILD_OPENBLAS=ON \
        -DMT_BUILD_VISUAL_TOOLS=ON \
        -DMT_BUILD_C3D=OFF \
        -DMT_USE_OPENMP=ON \
        -DUSE_SYSTEM_GLUT=ON \
        -DBUILD_TESTING=ON \
        -DMT_PACKAGES_PATH=/opt/quarantine/software/minc-toolkit-v2/packagecache &&
```

All tests also pass.

**Comment by gdevenyi** [comment]
After this gets merged, I'd like to tag/release 1.9.18.2

**Comment by gdevenyi** [comment]
Should we default to building openblas so the default config is confirmed buildable?

**Comment by gdevenyi** [comment]
Updated FREEGLUT version to successfully build with the new gcc.

> @gdevenyi - building this branch on 22.04 I still hit #153 with external blas, so probably we should?

@bcdarwin ok, will flip the switch.

**Comment by bcdarwin** [comment]
Building for me now on Ubuntus 20.04 and 22.04.

**Comment by bcdarwin** [comment]
@gdevenyi - tag incoming?

**Comment by vfonov** [comment]
check if it still builds fro CentOS 7

**Comment by bcdarwin** [comment]
so one general issue is that minc-toolkit-config.sh sets LD_LIBRARY_PATH, and when this contains a BLAS it breaks numpy :)

**Comment by bcdarwin** [comment]
rebuilding on centos now

**Comment by gdevenyi** [comment]
Tag and release ready

**Comment by bcdarwin** [comment]
Build succeeded, though I didn't build the visual tools or ANTs/Elastix, but ABC, patch_morphology are fine;
 all tests pass.

**Pull request merged**
